name: 'PR Opened Actions'

on:
    pull_request_target:
        types:
            - opened
            - reopened

jobs:
    process-asana-tasks:
        runs-on: ubuntu-latest
        steps:
            - name: Add comment to Asana task(s)
              uses: noisysocks/native-github-asana-sync@2f7adf9cbd90a5cd971498919f4d9c5831143a29
              with:
                  action: 'add-asana-comment'
                  asana-pat: ${{ secrets.ASANA_ACCESS_TOKEN }}
                  trigger-phrase: 'Task/Issue URL:'
                  asana-project: '1203268166580279' # CPM (Cookie Pop-up Management) Triage project

            - name: Find Asana task ID(s)
              id: find-tasks
              uses: noisysocks/native-github-asana-sync@2f7adf9cbd90a5cd971498919f4d9c5831143a29
              with:
                  action: 'find-asana-task-ids'
                  asana-pat: ${{ secrets.ASANA_ACCESS_TOKEN }}
                  trigger-phrase: 'Task/Issue URL:'
                  asana-project: '1203268166580279' # CPM (Cookie Pop-up Management) Triage project

            - name: Move task(s) to "Awaiting review" section
              if: steps.find-tasks.outputs.asanaTaskIds
              uses: noisysocks/native-github-asana-sync@2f7adf9cbd90a5cd971498919f4d9c5831143a29
              with:
                  action: 'add-task-asana-project'
                  asana-pat: ${{ secrets.ASANA_ACCESS_TOKEN }}
                  asana-project: '1203268166580279' # CPM (Cookie Pop-up Management) Triage project
                  asana-section: '1209767000096488' # "Awaiting review" section ID
                  asana-task-id: ${{ steps.find-tasks.outputs.asanaTaskIds }}
